# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-06-19 12:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0003_auto_20190619_1453'),
    ]

    operations = [
        migrations.CreateModel(
            name='Followers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(default='', max_length=40)),
                ('Follower', models.CharField(default='', max_length=40)),
            ],
        ),
    ]
