# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-06-25 11:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0005_auto_20190619_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='instagram.Image'),
            preserve_default=False,
        ),
    ]
